- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    become: true
    become_user: root
    dnf:
      state: latest
      name:
        - terminator
        - git
        - openssl
        - thunderbird
        - arp-scan
        - vlc
        - gimp
        - hexchat
        - nmap
        - zsh
        - flameshot
        - 

